name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Formatting
        run: cargo fmt -- --check


  lint:
    name: Lint
    needs: [format]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Rust Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings


  test:
    name: Test
    needs: [lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Rust Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install latest nextest release
      uses: taiki-e/install-action@nextest

    - name: Run tests
      run: cargo nextest run --config-file ${{ github.workspace }}/.github/nextest.toml --profile ci